# netlify.toml
[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Roda a função após cada deploy bem-sucedido
[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions"